### PR TITLE
Main

### PR DESCRIPTION
**Pull request by dsmith270**
Fix that allows the User Principal held in HttpSession to be Serialized. This is required for the web.xml distributable tag to work.

### CODE REVIEW

**Comment by siddhijain** [comment]
@dsmith270 Can you elaborate on the purpose of this PR?

**Comment by dsmith270** [comment]
Hi Siddhi,

Thanks for asking. MSAL doesn’t currently work with the <distributable/> tag in web.xml for J2EE apps. You can try this code with a logged in user in a Servlet or a jsp page:

       public boolean serializeUserPrincipal() {

                IAuthenticationResult result = (IAuthenticationResult) session.getAttribute(Constants.PRINCIPAL_SESSION_NAME);
                if (result == null) {
                        throw new RuntimeException("please log in first");
                }

                ByteArrayOutputStream bout=new ByteArrayOutputStream();
                ObjectOutputStream out;
                try {
                        out = new ObjectOutputStream(bout);
                        out.writeObject(result);
                        out.flush();
                } catch (IOException e) {
                        e.printStackTrace();
                        return false;
                }

                byte [] bytes = bout.toByteArray();
                ByteArrayInputStream bin = new ByteArrayInputStream(bytes);

                IAuthenticationResult output;
                try {
                        ObjectInputStream instr = new ObjectInputStream(bin);
                        output = (IAuthenticationResult) instr.readObject();
                } catch (IOException e) {
                        e.printStackTrace();
                        return false;
                } catch (ClassNotFoundException e) {
                        e.printStackTrace();
                        return false;
                }

                System.err.println(output);
                return true;

        }

This will fail currently. That means it’s not possible to use the normal J2EE session replication which is found in many of our apps. Here are some details on the J2EE standard mechanism, at least as found in JBoss such as we are using at DoE:

https://docs.jboss.org/jbossas/docs/Clustering_Guide/beta422/html/clustering-http-app.html

Sincerely,


David R. Smith

2IC/Middleware Support
Infrastructure Services
Information Technology Directorate

M: 0407 466 058
E: ***@***.***?subject=Contact%20Dave>

 ***@***.***

  8 Central  Avenue
  Australian Technology Park
  Eveleigh NSW 2015
  www.dec.nsw.gov.au

**Comment by dsmith270** [comment]
@siddhijain Any update on this?

**Review by siddhijain — APPROVED** [review]
Looks good to me.

**Pull request merged**
